<a href="https://colab.research.google.com/github/Amarmurun0212/Diver/blob/main/AI%26MLLes6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# OOP обьект хандалт программчлалын талаар авч үзье

# класс. класс нь загвар бөгөөд түүнээс обьектууд үүснэ


*   Класс нь обьектын бүтэц болон шинж чанарыг тодорхойлж өгдөг
*   Шинэ обьект үүсгэхдээ Template  байдлаар ашигладаг
*   обьектын initial state, attribute(nud bailaa gehed bor), method(yu hiij chaddaggiig)-уудыг классаар зохицуулж тодорхойлж болдог



Жишээ нь:

Car класс → машины ерөнхий загвар
car1, car2 → тухайн классын объектууд

Класс үүсгэх

Python-д class түлхүүр үгээр класс тодорхойлно.

In [ ]:
# Class
class Dog:
    pass

In [ ]:
#classaa duudwal class bairlaj baigaa haygiig nadad gargaj ugnu
Dog

__main__.Dog

__init__() — Constructor

Объект үүсэхэд автоматаар ажилладаг функц.

In [ ]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age

__init__() — Constructor

Объект үүсэхэд автоматаар ажилладаг функц.

In [ ]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age

Объект үүсгэх:

In [ ]:
dog1 = Dog("Buddy", 3)

print(dog1.name)
print(dog1.age)

Buddy
3


self гэж юу вэ?

self нь тухайн объект өөрөө.

In [ ]:
# self.name “энэ объектын name утга”

Method (Классын функц)

Класс доторх функцийг method гэдэг.

In [ ]:
class Dog:
    def __init__(self, name):
        self.name = name

    def bark(self):
        print(self.name, "Гүйж байна!")

In [ ]:
# Ашиглах
dog1 = Dog("Bob")
dog1.bark()

Bob Гүйж байна!


Attribute (Өгөгдөл)

Класс дотор хадгалж буй хувьсагч.
self.name
self.age

In [ ]:
class Student:
    def __init__(self, name, grade):
        self.name = name
        self.grade = grade

    def introduce(self):
        print("Намайг", self.name, "гэдэг.")
        print("Миний дүн:", self.grade)

student1 = Student("Anu", 95)

student1.introduce()

Намайг Anu гэдэг.
Миний дүн: 95


Inheritance (Удамшил)

Нэг класс нөгөөгөөс шинж чанар өвлөнө.

In [ ]:
class Animal:
    def speak(self):
        print("Амьтан дуу гаргаж байна")

class Dog(Animal):
    pass

d = Dog()
d.speak()

Амьтан дуу гаргаж байна


In [ ]:
# VEHICLE CLASS
# Бүх тээврийн хэрэгслийн үндсэн класс
class Vehicle:
  # Vehicle тээврийн хэрэгсэл
    # Constructor
    # Обьект үүсэхэд ажиллана
    def __init__(self, brand, model, year):
        # Обьектын өгөгдөл
        self.brand = brand
        self.model = model
        self.year = year
        # Машин асаалттай эсэх
        self.is_running = False
    # Машин асаах
    def start(self):
        self.is_running = True
        print(self.brand, self.model, "аслаа.")
    # Машин унтраах
    def stop(self):
        self.is_running = False
        print(self.brand, self.model, "унтарлаа.")
    # Машины мэдээлэл
    def info(self):
        print("----- INFO -----")
        print("Brand :", self.brand)
        print("Model :", self.model)
        print("Year  :", self.year)
        if self.is_running:
            print("Status: Асаалттай")
        else:
            print("Status: Унтарсан")
# CAR CLASS
# Vehicle-ээс удамшиж байна
class Car(Vehicle):
    # fuel_type нэмсэн constructor
    def __init__(self,
                 brand,
                 model,
                 year,
                 fuel_type):
        # Parent constructor
        super().__init__(brand, model, year)
        # Шинэ attribute
        self.fuel_type = fuel_type
    # Машин жолоодох
    def drive(self):

        if self.is_running:
            print(self.brand, self.model, "явж байна.")
        else:
            print("Эхлээд асаана уу.")
# ==========================================
# ELECTRIC CAR CLASS
# Car-оос удамшиж байна
# ==========================================
class ElectricCar(Car):
    # battery_capacity нэмсэн constructor
    def __init__(self,
                 brand,
                 model,
                 year,
                 fuel_type,
                 battery_capacity):
        # Parent constructor
        super().__init__(brand,
                         model,
                         year,
                         fuel_type)
        # Battery хэмжээ
        self.battery_capacity = battery_capacity
    # Цэнэглэх method
    def charge(self):
        print(self.brand, self.model, "цэнэглэж байна.")
    # Method overriding
    # start()-ийг өөрчилж байна
    def start(self):

        self.is_running = True

        print(self.brand,
              self.model,
              "чимээгүй аслаа.")
# OBJECT ҮҮСГЭХ
car1 = Car("Toyota",
           "Camry",
           2020,
           "Petrol")
tesla1 = ElectricCar("Tesla",
                     "Model S",
                     2024,
                     "Electric",
                     "100 kWh")
# CAR TEST
print("\n=== CAR TEST ===\n")
car1.info()
print()
car1.start()
print()
car1.drive()
print()
car1.stop()
# ==========================================
# TESLA TEST
# ==========================================
print("\n=== TESLA TEST ===\n")
tesla1.info()
print()
tesla1.start()
print()
tesla1.drive()
print()
tesla1.charge()
print()
tesla1.stop()


=== CAR TEST ===

----- INFO -----
Brand : Toyota
Model : Camry
Year  : 2020
Status: Унтарсан

Toyota Camry аслаа.

Toyota Camry явж байна.

Toyota Camry унтарлаа.

=== TESLA TEST ===

----- INFO -----
Brand : Tesla
Model : Model S
Year  : 2024
Status: Унтарсан

Tesla Model S чимээгүй аслаа.

Tesla Model S явж байна.

Tesla Model S цэнэглэж байна.

Tesla Model S унтарлаа.


NumPy гэдэг нь numiracal Python

дата анализ болон шинжлэх ухааны хүнд тооцооллуудыг маш өндөр хурдтайгаар хийж чаддаг сан


*   n хэмжээстэй массивыг хурдан болон зайны ашигтай зохион байгуулалттайгаар хийдэг
*   Үндсэн математик функцуудыг ямарч давталт ашиглахгүйгээр шууд массивын бүх элементүүд дээр хийх боломжтой
* шугаман алгебрын функцүүл
 * санамсаргүй тоо үүсгэх
 * фурьегийн хувиргалт функцууд
 * C / C++/ Fortan дээр бичигдсэн функцууд



Олон хэмжээст массив array төрлийн обьект үүсгэх

In [ ]:
import numpy as np

In [ ]:
data_1 = [6,5.3,4,56,7,0,1]

In [ ]:
arr1 = np.array(data_1)

In [ ]:
arr1

array([ 6. ,  5.3,  4. , 56. ,  7. ,  0. ,  1. ])

In [ ]:
data_2 = [[1,2,3,4],[5,6,7,8]]

In [ ]:
arr2 = np.array(data_2)

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3 = np.array(data_2,float)

In [ ]:
arr3

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [ ]:
arr3[1]

array([5., 6., 7., 8.])

In [ ]:
arr3[1,2]

np.float64(7.0)

In [ ]:
# vvsgeh
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# array shalgah
#2 hemjeest array
arr2.ndim

2

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.size

8

#Pandas сан

In [ ]:
# Pandas санг импорт хийх
import pandas as pd
# -----------------------------
# 1. DataFrame үүсгэх
# -----------------------------

# Python dictionary ашиглан өгөгдөл үүсгэнэ
data = {
    "Нэр": ["Ариун", "Болд", "Сараа", "Тэмүүжин"],
    "Нас": [20, 21, 19, 22],
    "Оноо": [85, 92, 78, 95]
}

# DataFrame бол хүснэгтэн өгөгдөл
df = pd.DataFrame(data)

print("=== Бүх өгөгдөл ===")
print(df)


# -----------------------------
# 2. Эхний мөрүүдийг харах
# -----------------------------

print("\n=== Эхний 2 мөр ===")
print(df.head(2))


# -----------------------------
# 3. Нэг багана сонгох
# -----------------------------

print("\n=== Нэр багана ===")
print(df["Нэр"])


# -----------------------------
# 4. Нөхцөлөөр шүүх (filter)
# -----------------------------

# Оноо нь 90-ээс их хүмүүсийг авах
high_score = df[df["Оноо"] > 90]

print("\n=== 90-ээс дээш оноотой хүмүүс ===")
print(high_score)


# -----------------------------
# 5. Шинэ багана нэмэх
# -----------------------------

# Тэнцсэн эсэхийг шинэ багана болгоно
df["Тэнцсэн"] = df["Оноо"] >= 80

print("\n=== Шинэ багана нэмсний дараа ===")
print(df)


# -----------------------------
# 6. Дундаж тооцоолох
# -----------------------------

average_score = df["Оноо"].mean()

print("\n=== Дундаж оноо ===")
print(average_score)


# -----------------------------
# 7. Хамгийн өндөр оноо
# -----------------------------

max_score = df["Оноо"].max()

print("\n=== Хамгийн өндөр оноо ===")
print(max_score)


# -----------------------------
# 8. Мөрөөр хандах
# -----------------------------

print("\n=== 1-р индексийн мэдээлэл ===")
print(df.loc[1])


# -----------------------------
# 9. CSV файл хадгалах
# -----------------------------

# index=False гэвэл мөрийн дугаар хадгалахгүй
df.to_csv("students.csv", index=False)

print("\nCSV файл амжилттай хадгалагдлаа!")

=== Бүх өгөгдөл ===
        Нэр  Нас  Оноо
0     Ариун   20    85
1      Болд   21    92
2     Сараа   19    78
3  Тэмүүжин   22    95

=== Эхний 2 мөр ===
     Нэр  Нас  Оноо
0  Ариун   20    85
1   Болд   21    92

=== Нэр багана ===
0       Ариун
1        Болд
2       Сараа
3    Тэмүүжин
Name: Нэр, dtype: object

=== 90-ээс дээш оноотой хүмүүс ===
        Нэр  Нас  Оноо
1      Болд   21    92
3  Тэмүүжин   22    95

=== Шинэ багана нэмсний дараа ===
        Нэр  Нас  Оноо  Тэнцсэн
0     Ариун   20    85     True
1      Болд   21    92     True
2     Сараа   19    78    False
3  Тэмүүжин   22    95     True

=== Дундаж оноо ===
87.5

=== Хамгийн өндөр оноо ===
95

=== 1-р индексийн мэдээлэл ===
Нэр        Болд
Нас          21
Оноо         92
Тэнцсэн    True
Name: 1, dtype: object

CSV файл амжилттай хадгалагдлаа!
