<a href="https://colab.research.google.com/github/Amarmurun0212/Diver/blob/main/Amarmurun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Статистика
Вы измеряете физическую величину, например, давление, следите, чтобы оно не превышало 5 атм.

Получили ряд измерений, при этом условия процесса не менялись. Давление на самом деле было постоянным.

Измерения: (5.2, 4.3, 4.7, 4.9 , 5.5) атм.

С какой вероятностью давление
* ниже 5 атм?
* ниже 4 атм?

ниже 5 атм = 3/5

ниже 4 атм = 0/5

In [2]:
import numpy as np

In [3]:
p = [5.2, 4.3, 4.7, 4.9, 5.5]
p

[5.2, 4.3, 4.7, 4.9, 5.5]

In [4]:
pn = np.array(p)
pn

array([5.2, 4.3, 4.7, 4.9, 5.5])

In [5]:
a = pn[:]<5
a

array([False,  True,  True,  True, False])

In [6]:
print('Вероятность меньше 5 =',a.sum()/a.size)


Вероятность меньше 5 = 0.6


In [7]:
b = pn[:]<4
b

array([False, False, False, False, False])

In [9]:
print('Вероятность меньше 4 =',b.sum()/b.size)

Вероятность меньше 4 = 0.0


## 2. Теория вероятностей
Два лучника стреляют в мишень.

Когда они независимо стреляют, тренируются, то первый из них попадает в мишень с вероятностью 70%, а второй - 55%.

Теперь они выстрелили вместе. В результате в мишени торчит одна стрела.

Вопрос: какова вероятность, что попал первый лучник, а какова - что второй?

### Оценка
* Правильный ответ - 30 баллов
* Правильный подход при неправильном ответе - 15 баллов


In [10]:
p1 = 70
p1

70

In [11]:
p2 =55
p2

55

In [12]:
p1 = p1/100
p1

0.7

In [13]:
p2 = p2/100
p2

0.55

In [14]:
p1Up2 = p1*p2
print('оба попадают',p1Up2)

оба попадают 0.385


In [15]:
pl = p1+p2-p1Up2
pl=pl*100
print('один из них попадает',pl)

один из них попадает 86.5


## 3. Машинное обучение
Загрузите данные о полетах пассажирских самолетов в США из файлов flight_delays_test.csv и flight_delays_train.csv
Описание:
* Month - месяц (с-8 значит август),
* DayofMonth - число месяца (с-21 - 21е число),
* DayOfWeek - день недели (с-7 значит воскресенье),
* DepTime - время вылета (две последние цифры - минуты, перед ними - часы)
* UniqueCarrier - код авиакомпании,
* Origin - код аэропорта вылета,
* Dest - код аэропорта назначения,
* Distance - расстояние между аэропортами вылета и назначения

Требуется определить, с какой вероятностью рейс задержится более чем на 15 минут

* dep_delayed_15min - метка задержки (N - задержался меньше 15 минут, Y - больше)

Метки содержатся в тренировочном сете и не содержатся в тестовом.
Требуется добавить вероятность метки Y в тестовом сете и сохранить его с метками.

Метрика оценки - ROC AUC по вероятности предсказания (см. пример ниже)


In [16]:
import pandas as pd
df = pd.read_csv('flight_delays_train.csv')
df.head

<bound method NDFrame.head of       Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance  \
0       c-8       c-21       c-7     1934            AA    ATL  DFW       732   
1       c-4       c-20       c-3     1548            US    PIT  MCO       834   
2       c-9        c-2       c-5     1422            XE    RDU  CLE       416   
3      c-11       c-25       c-6     1015            OO    DEN  MEM       872   
4      c-10        c-7       c-6     1828            WN    MDW  OMA       423   
...     ...        ...       ...      ...           ...    ...  ...       ...   
99995   c-5        c-4       c-3     1618            OO    SFO  RDD       199   
99996   c-1       c-18       c-3      804            CO    EWR  DAB       884   
99997   c-1       c-24       c-2     1901            NW    DTW  IAH      1076   
99998   c-4       c-27       c-4     1515            MQ    DFW  GGG       140   
99999  c-11       c-17       c-4     1800            WN    SEA  SMF       605  

In [17]:
train_x = df.iloc[:,:8]
train_x

Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance
0       c-8       c-21       c-7     1934            AA    ATL  DFW       732
1       c-4       c-20       c-3     1548            US    PIT  MCO       834
2       c-9        c-2       c-5     1422            XE    RDU  CLE       416
3      c-11       c-25       c-6     1015            OO    DEN  MEM       872
4      c-10        c-7       c-6     1828            WN    MDW  OMA       423
...     ...        ...       ...      ...           ...    ...  ...       ...
99995   c-5        c-4       c-3     1618            OO    SFO  RDD       199
99996   c-1       c-18       c-3      804            CO    EWR  DAB       884
99997   c-1       c-24       c-2     1901            NW    DTW  IAH      1076
99998   c-4       c-27       c-4     1515            MQ    DFW  GGG       140
99999  c-11       c-17       c-4     1800            WN    SEA  SMF       605

[100000 rows x 8 columns]

In [18]:
train_y = df.iloc[:,8:]
train_y

dep_delayed_15min
0                     N
1                     N
2                     N
3                     N
4                     Y
...                 ...
99995                 N
99996                 N
99997                 N
99998                 N
99999                 N

[100000 rows x 1 columns]

In [19]:
from sklearn.preprocessing import LabelEncoder
for i in range(8):
  le = LabelEncoder()
  le.fit(train_x.iloc[:,i])
  train_x.iloc[:,i]=le.transform(train_x.iloc[:,i])
train_x

<ipython-input-19-a429e2d5f7e7>:5: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  train_x.iloc[:,i]=le.transform(train_x.iloc[:,i])
<ipython-input-19-a429e2d5f7e7>:5: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  train_x.iloc[:,i]=le.transform(train_x.iloc[:,i])
<ipython-input-19-a429e2d5f7e7>:5: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.

Month  DayofMonth  DayOfWeek  DepTime  UniqueCarrier  Origin  Dest  \
0         10          13          6     1017              0      18    78   
1          6          12          2      791             18     217   171   
2         11          11          4      705             20     228    59   
3          2          17          5      458             15      78   175   
4          1          28          5      951             19     174   199   
...      ...         ...        ...      ...            ...     ...   ...   
99995      7          25          2      821             15     246   224   
99996      0           9          2      327              4      92    72   
99997      0          16          1      984             13      85   131   
99998      6          19          3      758             12      79   107   
99999      2           8          3      923             19     245   253   

       Distance  
0           577  
1           651  
2           306  
3           683  
4           313  
...         ...  
99995       106  
99996       691  
99997       828  
99998        55  
99999       469  

[100000 rows x 8 columns]

In [20]:
from sklearn.tree import DecisionTreeClassifier

dtm = DecisionTreeClassifier()
dtm.fit(train_x,train_y)

DecisionTreeClassifier()

In [21]:
df_test = pd.read_csv('flight_delays_test.csv')
df_test.head

<bound method NDFrame.head of       Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance
0       c-7       c-25       c-3      615            YV    MRY  PHX       598
1       c-4       c-17       c-2      739            WN    LAS  HOU      1235
2      c-12        c-2       c-7      651            MQ    GSP  ORD       577
3       c-3       c-25       c-7     1614            WN    BWI  MHT       377
4       c-6        c-6       c-3     1505            UA    ORD  STL       258
...     ...        ...       ...      ...           ...    ...  ...       ...
99995   c-6        c-5       c-2      852            WN    CRP  HOU       187
99996  c-11       c-24       c-6     1446            UA    ORD  LAS      1515
99997   c-1       c-30       c-2     1509            OO    ORD  SGF       438
99998   c-1        c-5       c-5      804            DL    LGA  ATL       761
99999  c-10       c-29       c-1      834            OO    MKE  MSP       297

[100000 rows x 8 columns]>

In [22]:
test_x = df_test
for i in range(8):
  le.fit(test_x.iloc[:,i])
  test_x.iloc[:,i]=le.transform(test_x.iloc[:,i])
test_x

<ipython-input-22-483389f38849>:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  test_x.iloc[:,i]=le.transform(test_x.iloc[:,i])
<ipython-input-22-483389f38849>:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  test_x.iloc[:,i]=le.transform(test_x.iloc[:,i])
<ipython-input-22-483389f38849>:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.iset

Month  DayofMonth  DayOfWeek  DepTime  UniqueCarrier  Origin  Dest  \
0          9          17          2      221             19     194   217   
1          6           8          1      305             17     155   129   
2          3          11          6      257             11     121   208   
3          5          17          6      820             17      49   183   
4          8          27          2      751             15     209   270   
...      ...         ...        ...      ...            ...     ...   ...   
99995      8          26          1      378             17      70   129   
99996      2          16          5      732             15     209   154   
99997      0          23          1      755             14     209   254   
99998      0          26          4      330              6     162    19   
99999      1          21          0      360             14     186   196   

       Distance  
0           456  
1           930  
2           438  
3           268  
4           156  
...         ...  
99995        89  
99996      1026  
99997       322  
99998       600  
99999       193  

[100000 rows x 8 columns]

In [23]:
result =dtm.predict(test_x)
resultdf = pd.DataFrame(result, columns = ['result'])
resultdf

result
0          Y
1          N
2          N
3          N
4          N
...      ...
99995      N
99996      N
99997      N
99998      N
99999      N

[100000 rows x 1 columns]

In [24]:
testdf = pd.read_csv('flight_delays_test.csv')

last = pd.concat([testdf, resultdf], axis=1)
last.to_csv('result.csv')

## 4. Междисциплинарная задача
Есть узел, в который подходит три трубы, как на рисунке.

![title](3Pipes.png)
Приборы на трубах показывают, что в узел поступает 90, по левой трубе уходит 35, а по правой - 60. Чего именно - не важно, это может быть электрический ток, расход воды и т.п. Важно, что в узле нет ни потерь, ни источников.

Вопрос состоит в том, сколько на самом деле течет по каждой из труб.

### Оценка
* Правильный подход - 50 баллов
* Правильный ответ - еще 25 баллов

(90 +- x) =(35+-x)+ (60+-x)