<a href="https://colab.research.google.com/github/Amarmurun0212/Diver/blob/main/Implementation_of_matrix_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Problem 1] Matrix product is calculated manually


In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_ndarray = np.dot(a_ndarray, b_ndarray)
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
